### ISSUE TITLE
All the messages appear in the same row

### ISSUE THREAD

**Issue by Kopp35345** [m1st4x/RimStory#1]
As the title says all the events happened are written in the same row. 
I am playing the lastest version 1.2.2753 and it also happens if the only loaded mods are Harmony, HugsLib, ModManager and of course RimStory.
Greetings

*I cant add the picture I want so I uploaded it somewhere else.
https://postimg.cc/MXVS1xny

**Comment by m1st4x** [comment]
Hi, thanks for your report. Please check latest release. This should no longer be an issue.
Greetings
